version: '3.1'

services:
  db:
    image: mysql
    container_name: mysql_order
    restart: always
    environment:
      MYSQL_DATABASE: order
      MYSQL_USER: order
      MYSQL_PASSWORD: order
      MYSQL_ROOT_PASSWORD: order
    ports:
      - "5013:3306"
    # (this is just an example, not intended to be a production configuration)

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    ports:
      - "5022:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: order

