
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false  # one doesn't need to register itself as a client(It means about discovery-server)
    fetch-registry: false
server:
  port: 8761 # is the default port where Eureka runs
