spring:
  datasource:
    url: jdbc:mysql://localhost:5014/inventory
    username: inventory
    password: inventory
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update



server:
  port: 8084