spring:
  datasource:
    url: jdbc:mysql://localhost:5014/inventory
    username: inventory
    password: inventory
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: "inventory-service"

  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 0

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
## preferIpAddress: true